### ISSUE TITLE
Test_charC1_bool_true_db fails

### ISSUE THREAD

**Issue by tgulacsi** [ranaian/ora#11]
How should the char(1) column be read as a bool?

tgulacsi@tgulacsi-Aspire-V3-371:~/src/github.com/ranaian/ora$ go test -run=bool
Read environment variable GO_ORA_DRV_TEST_DB = '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=49161)))(CONNECT_DATA=(SERVICE_NAME=xe)))'
Read environment variable GO_ORA_DRV_TEST_USERNAME = 'test'
Read environment variable GO_ORA_DRV_TEST_PASSWORD = 'test'
Read session time zone from database...
Dropping previous tables...
--- FAIL: Test_charC1_bool_true_db (0.12s)
        tstlg.go:18: ORA I E1C2] Prepare
        tstlg.go:18: ORA I E1S2S1] Prep: create table t3 (c1 char(1 char) not null)
        tstlg.go:18: ORA I E1S2S1S1] Exec
        tstlg.go:18: ORA I E1S2S1S1] Close
        tstlg.go:18: ORA I E1S2S1S1] Close
        tstlg.go:18: ORA I E1C2] Prepare
        tstlg.go:18: ORA I E1S2S1] Prep: insert into t3 (c1) values (:c1)
        tstlg.go:18: ORA I E1S2S1S1] Exec
        tstlg.go:18: ORA I E1C2] Prepare
        tstlg.go:18: ORA I E1S2S1] Prep: select c1 from t3
        tstlg.go:18: ORA I E1S2S1S1] Query
        tstlg.go:18: ORA I E1S2S1S1R0] open
        z_oracle_test.go:1844: Unable to cast actual value to bool, *bool, ora.Bool. (string, 1): goroutine 8 [running]:
                github.com/ranaian/ora.compare(0x6367e0, 0xc208011f00, 0x638160, 0xc2080925a0, 0x19, 0xc2080201b0)
                        /home/tgulacsi/src/github.com/ranaian/ora/z_oracle_test.go:1211 +0x4a6
                github.com/ranaian/ora.testBindDefineDB(0x6367e0, 0xc208011f00, 0xc2080201b0, 0x702e30, 0x15)
                        /home/tgulacsi/src/github.com/ranaian/ora/z_oracle_test.go:268 +0xa12
                github.com/ranaian/ora.Test_charC1_bool_true_db(0xc2080201b0)
                        /home/tgulacsi/src/github.com/ranaian/ora/z_db_test.go:209 +0x8f
                testing.tRunner(0xc2080201b0, 0xa4e970)
                        /usr/local/go/src/testing/testing.go:454 +0x9b
                created by testing.RunTests
                        /usr/local/go/src/testing/testing.go:562 +0xa3e
        tstlg.go:18: ORA I E1S2S1S1] Close
        tstlg.go:18: ORA I E1S2S1S1] Close
        tstlg.go:18: ORA I E1S2S1S1R0] close
        tstlg.go:18: ORA I E1S2S1S1] Close
        tstlg.go:18: ORA I E1S2S1S1] Close
        tstlg.go:18: ORA I E1C2] Prepare
        tstlg.go:18: ORA I E1S2S1] Prep: drop table t3
        tstlg.go:18: ORA I E1S2S1S1] Exec
        tstlg.go:18: ORA I E1S2S1S1] Close
        tstlg.go:18: ORA I E1S2S1S1] Close
--- FAIL: Test_charC1Null_bool_true_db (0.11s)
        z_oracle_test.go:1844: Unable to cast actual value to bool, *bool, ora.Bool. (string, 1): goroutine 9 [running]:
                github.com/ranaian/ora.compare(0x6367e0, 0xc208092b60, 0x638160, 0xc208093210, 0x19, 0xc208020240)
                        /home/tgulacsi/src/github.com/ranaian/ora/z_oracle_test.go:1211 +0x4a6
                github.com/ranaian/ora.testBindDefineDB(0x6367e0, 0xc208092b60, 0xc208020240, 0x702e70, 0x11)
                        /home/tgulacsi/src/github.com/ranaian/ora/z_oracle_test.go:268 +0xa12
                github.com/ranaian/ora.Test_charC1Null_bool_true_db(0xc208020240)
                        /home/tgulacsi/src/github.com/ranaian/ora/z_db_test.go:213 +0x81
                testing.tRunner(0xc208020240, 0xa4e988)
                        /usr/local/go/src/testing/testing.go:454 +0x9b
                created by testing.RunTests
                        /usr/local/go/src/testing/testing.go:562 +0xa3e

**Comment by ranaian** [comment]
Yes, the char(1) column should be read as a bool in the Test_charC1_bool_true_db test.

**Comment by tgulacsi** [comment]
Ok, but what shall do the conversion?

**Comment by tgulacsi** [comment]
Ok, I've found the reason: char(1 char) results in columnSize=4 (I think this is because AL32UTF8 charset): https://github.com/ranaian/ora/pull/18

**Comment by ranaian** [comment]
Nice find
