### ISSUE TITLE
glog automatic flag registering

### ISSUE THREAD

**Issue by tgulacsi** [ranaian/ora#6]
I do love glog, but hate its flag usage, which is hardly avoidable.
But why should my main program 
a) manage the creation of flags by importing "ora",
b) forced to use glog, if it'd use some other logging package?

I like gopkg.in/inconshreveable/log15.v2 as it is a well mannered package: for libraries, I can SetHandler(log15.DiscardHandler()), and in tests/main application I can set for other destinations, if wanted.

But I don't want to force anything, especially if you know some trick to disable glog's automatic flag registering.

**Comment by ranaian** [comment]
Hi Tamás,

Will merge your pull requests when i have time later today.
LDFLAGS change needs some work on my side for windows.
I hear you about the logging and forcing on the flags. I'm not attached to
glog. I was hoping to have zero external library dependencies. I'll have a
close look at log15. Looks like a solid package. I would like to test it a
bit. I think there is some value in using a package backed by Google. This
gets into 3rd party package dilemma where there isn't necessarily a solid
standard in Go standard library and others will have a favorite logging
packages, possibly with more features. What do you think of having
pluggable logging mechanism so anyone can pick and choose their favorite
logging?

**Comment by tgulacsi** [comment]
I think that glog is fantastic for applications (automatic file handling,
rotation...), but a little bit obtrusive for libs.

As I see you use glog.Info 26 times, glog.Error 6 times, and nothing else
(glog.V(n)...), so don't need more than an interface with Infof, Infoln,
Errorf and Errorln methods, and a glog-based implementation (or else). Then
anybody can replace the Log variable with her own Logger implementation.



2015-05-19 22:38 GMT+02:00 ranaian <notifications@github.com>:

**Comment by tgulacsi** [comment]
I've implemented a "minimal viable product" as 49d2e08
