### ISSUE TITLE
"ORA-01000: maximum open cursors exceeded" in tests

### ISSUE THREAD

**Issue by tgulacsi** [ranaian/ora#9]
Running 
  LC_ALL=C NLS_LANG=AMERICAN_AMERICA.AL32UTF8 go test

After a few hundred records I get

2015/05/21 11:58:27 E2S1S1] Prep: create table t129_1 (c1 interval day to second(9) null)
2015/05/21 11:58:27 E2S1S1S25] Close
2015/05/21 11:58:27 E2S1S1] Prep: insert into t129_1 (c1) values (:c1)
2015/05/21 11:58:27 E2S1S1] Prep: select c1 from t129_1
2015/05/21 11:58:27 E2S1S1S1R0] open
2015/05/21 11:58:27 E2S1S1S1] Close
2015/05/21 11:58:27 E2S1S1S1R0] close
2015/05/21 11:58:27 E2S1S1S25] Close
2015/05/21 11:58:27 E2S1S1] Prep: drop table t129_1
2015/05/21 11:58:27 E2S1S1S1] Close
--- FAIL: TestBindDefine_OraIntervalDS_intervalDSNull_null_session (0.07s)
        z_oracle_test.go:754: ora: ORA-01000: maximum open cursors exceeded

**Comment by ranaian** [comment]
I encountered this as well. I resolved the issue by [increasing the number of max open cursors](http://stackoverflow.com/questions/16676859/how-to-update-cursor-limit-for-ora-01000-maximum-open-cursors-exceed) on the Oracle server.

I'm not clear on whether the ora package has the opportunity to release non-named cursors faster. It would definitely be helpful to have a definitive answer.

**Comment by tgulacsi** [comment]
What limit is enough for the tests?
2015. máj. 21. du. 6:54 ezt írta ("ranaian" <notifications@github.com>):

**Comment by ranaian** [comment]
4000

**Comment by tgulacsi** [comment]
My other problem is the RSS memory usage: 1.8GiB for the full test. As I
profiled, get_bytes stood out.

2015-05-21 19:15 GMT+02:00 ranaian <notifications@github.com>:

**Comment by ranaian** [comment]
Ya, the driver needs improvement. I don't have time at the moment. You are welcome to optimize and improve as you see fit.

**Comment by ranaian** [comment]
documentation is updated to recommend increasing open_cursors to 4000.
